Repository jeffreyriosjr/jeffreys-drinks-ts, pull requests merged in 2021-05, with the labels that each got.

#8 Feat(app-router): add routers folder, AppRouter page inside with default setup
  src/routers/AppRouter.tsx
Labels: feature

#6 Feature: Navbar
  src/components/Navbar.tsx
Labels: feature

#17 Feat(types): created data types from the api references, added initial state type
  src/App.tsx
  src/components/Navbar.tsx
  src/routers/AppRouter.tsx
  src/types.d.ts
Labels: documentation, feature

#18 Feature: GlobalContext
  src/App.tsx
  src/context/GlobalContext.tsx
  src/pages/Homepage.tsx
  src/types.d.ts
Labels: feature

#20 feat(single-card): created single drink page using single card link to print
  src/components/Loader.tsx
  src/components/SingleDrinkComponent.tsx
  src/context/GlobalContext.tsx
  src/pages/SingleDrink.tsx
  src/routers/AppRouter.tsx
  src/types.d.ts
Labels: bug, help wanted

#21 feat(singleDrink-card): created single drink card component to show item with full details
  src/App.css
  src/components/SingleDrinkComponent.tsx
  src/pages/SingleDrink.tsx
Labels: documentation, help wanted

#22 Feature: DrinkCard
  src/components/DrinksCard.tsx
  src/components/Navbar.tsx
  src/pages/Homepage.tsx
Labels: feature

#31 feat(Css): final edit and style
  src/App.css
  src/components/DrinksCard.tsx
  src/components/Navbar.tsx
  src/components/SingleDrinkComponent.tsx
  src/pages/Homepage.tsx
  src/pages/SingleDrink.tsx
Labels: enhancement, feature
